### ISSUE TITLE
Connection not estaablishhed with mongodb server

### ISSUE THREAD

**Issue by prahaladbelavadi** [prahaladbelavadi/server-side-nodejs-hong-kong-university-coursera#1]
Trigger: `npm start`

Error log:

```
> conFusionServer@0.0.0 start C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer
> node ./bin/www

(node:13252) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Error: Unsupported host 'localhost:21017/conFusion/', hosts must be URL encoded and contain at most one unencoded slash
    at parseConnectionString (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\url_parser.js:243:11)
    at parseHandler (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\url_parser.js:129:14)
    at module.exports (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\url_parser.js:25:12)
    at deprecated (internal/util.js:66:15)
    at connect (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\operations\mongo_client_ops.js:180:3)
    at connectOp (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\operations\mongo_client_ops.js:284:3)
    at executeOperation (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\utils.js:420:24)
    at MongoClient.connect (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\mongo_client.js:168:10)
    at Promise (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongoose\lib\connection.js:521:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongoose\lib\connection.js:518:19)
    at Mongoose.connect (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongoose\lib\index.js:270:15)
    at Object.<anonymous> (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\app.js:19:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Comment by prahaladbelavadi** [comment]
Attempt to try and parse  {useMongoClient: true }

Error: No lonnger required usemongoclient;

----

```
> conFusionServer@0.0.0 start C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer
> node ./bin/www

WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.
    at handleUseMongoClient (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongoose\lib\connection.js:604:17)
    at NativeConnection.Connection.openUri (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongoose\lib\connection.js:480:7)
    at Mongoose.connect (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongoose\lib\index.js:270:15)
    at Object.<anonymous> (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\app.js:19:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\bin\www:7:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
(node:9560) DeprecationWarning: current URL string parser is deprecated,
and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Error: Unsupported host 'localhost:21017/conFusion/', hosts must be URL encoded and contain at most one unencoded slash
    at parseConnectionString (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\url_parser.js:243:11)
    at parseHandler (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\url_parser.js:129:14)
    at module.exports (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\url_parser.js:25:12)
    at deprecated (internal/util.js:66:15)
    at connect (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\operations\mongo_client_ops.js:180:3)
    at connectOp (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\operations\mongo_client_ops.js:284:3)
    at executeOperation (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\utils.js:420:24)
    at MongoClient.connect (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\mongo_client.js:168:10)
    at Promise (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongoose\lib\connection.js:521:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongoose\lib\connection.js:518:19)
    at Mongoose.connect (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongoose\lib\index.js:270:15)
    at Object.<anonymous> (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\app.js:19:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

```
---
Attempt to parse { useNewUrlParser: true }
---
```
AL2497@ALIPL0555 MINGW64 ~/Documents/learning/server-side-nodejs-hong-kong-university-coursera/conFusionServer (master)
$ npm start

> conFusionServer@0.0.0 start C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer
> node ./bin/www

{ MongoNetworkError: failed to connect to server [localhost:21017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:21017]
    at Pool.<anonymous> (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }

```
---
Unable to connect to  db
---
```
AL2497@ALIPL0555 MINGW64 ~/Documents/learning/server-side-nodejs-hong-kong-university-coursera/conFusionServer (master)
$ npm start

> conFusionServer@0.0.0 start C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer
> node ./bin/www

C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\operations\mongo_client_ops.js:466
      throw err;
      ^

MongoError: database names cannot contain the character '/'
    at Function.create (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb-core\lib\error.js:43:12)
    at validateDatabaseName (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\operations\db_ops.js:708:24)
    at new Db (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\db.js:181:3)
    at MongoClient.db (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\mongo_client.js:268:14)
    at C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongoose\lib\connection.js:527:62
    at result (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\utils.js:414:17)
    at executeCallback (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\utils.js:406:9)
    at err (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\operations\mongo_client_ops.js:286:5)
    at connectCallback (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\operations\mongo_client_ops.js:241:5)
    at process.nextTick (C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer\node_modules\mongodb\lib\operations\mongo_client_ops.js:463:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! conFusionServer@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the conFusionServer@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AL2497\AppData\Roaming\npm-cache\_logs\2019-01-02T07_39_54_890Z-debug.log
```

---
clear out slashes in db name for connection to db @ urlconnect
---
```
AL2497@ALIPL0555 MINGW64 ~/Documents/learning/server-side-nodejs-hong-kong-university-coursera/conFusionServer (master)
$ npm start

> conFusionServer@0.0.0 start C:\Users\AL2497\Documents\learning\server-side-nodejs-hong-kong-university-coursera\conFusionServer
> node ./bin/www

(node:4072) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Connected correctly to the server
```

**Comment by ayush-hash** [comment]
did you find the solution? I am facing the same problem.
